linters:
 enable-all: true
 disable:
   - golint
   - unparam
   - gochecknoinits
   - gochecknoglobals
   - gomnd
   - nolintlint
   - dupl
   - varnamelen
   - tagliatelle
   - wrapcheck
   - thelper
   - testpackage
   - paralleltest
   - ireturn
   - nlreturn
   - goerr113
   - exhaustivestruct
   - wsl
   - forcetypeassert
   - exhaustive
   - scopelint
   - revive
   - lll
   - interfacer
   - gosec
   - funlen
   - stylecheck
   - cyclop
   - forbidigo
   - gocognit
   - godox
   - gomoddirectives
