// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pki/approved_certificates.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ApprovedCertificates struct {
	Subject          string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectKeyId     string `protobuf:"bytes,2,opt,name=subject_key_id,json=subjectKeyId,proto3" json:"subject_key_id,omitempty"`
	PemCert          string `protobuf:"bytes,3,opt,name=pem_cert,json=pemCert,proto3" json:"pem_cert,omitempty"`
	SerialNumber     string `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Issuer           string `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	AuthorityKeyId   string `protobuf:"bytes,6,opt,name=authority_key_id,json=authorityKeyId,proto3" json:"authority_key_id,omitempty"`
	RootSubject      string `protobuf:"bytes,7,opt,name=root_subject,json=rootSubject,proto3" json:"root_subject,omitempty"`
	RootSubjectKeyId string `protobuf:"bytes,8,opt,name=root_subject_key_id,json=rootSubjectKeyId,proto3" json:"root_subject_key_id,omitempty"`
	IsRoot           bool   `protobuf:"varint,9,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	Owner            string `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *ApprovedCertificates) Reset()         { *m = ApprovedCertificates{} }
func (m *ApprovedCertificates) String() string { return proto.CompactTextString(m) }
func (*ApprovedCertificates) ProtoMessage()    {}
func (*ApprovedCertificates) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce3f4f36edbe99d, []int{0}
}
func (m *ApprovedCertificates) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApprovedCertificates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApprovedCertificates.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApprovedCertificates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovedCertificates.Merge(m, src)
}
func (m *ApprovedCertificates) XXX_Size() int {
	return m.Size()
}
func (m *ApprovedCertificates) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovedCertificates.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovedCertificates proto.InternalMessageInfo

func (m *ApprovedCertificates) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ApprovedCertificates) GetSubjectKeyId() string {
	if m != nil {
		return m.SubjectKeyId
	}
	return ""
}

func (m *ApprovedCertificates) GetPemCert() string {
	if m != nil {
		return m.PemCert
	}
	return ""
}

func (m *ApprovedCertificates) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *ApprovedCertificates) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *ApprovedCertificates) GetAuthorityKeyId() string {
	if m != nil {
		return m.AuthorityKeyId
	}
	return ""
}

func (m *ApprovedCertificates) GetRootSubject() string {
	if m != nil {
		return m.RootSubject
	}
	return ""
}

func (m *ApprovedCertificates) GetRootSubjectKeyId() string {
	if m != nil {
		return m.RootSubjectKeyId
	}
	return ""
}

func (m *ApprovedCertificates) GetIsRoot() bool {
	if m != nil {
		return m.IsRoot
	}
	return false
}

func (m *ApprovedCertificates) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func init() {
	proto.RegisterType((*ApprovedCertificates)(nil), "zigbeealliance.distributedcomplianceledger.pki.ApprovedCertificates")
}

func init() { proto.RegisterFile("pki/approved_certificates.proto", fileDescriptor_3ce3f4f36edbe99d) }

var fileDescriptor_3ce3f4f36edbe99d = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x52, 0xbb, 0x92, 0xd3, 0x30,
	0x14, 0x8d, 0x03, 0x79, 0x89, 0x90, 0xc9, 0x88, 0x0c, 0x28, 0x14, 0x26, 0x3c, 0x8a, 0x34, 0xb6,
	0x0b, 0xbe, 0x20, 0x81, 0x86, 0x61, 0x86, 0x22, 0xe9, 0x28, 0xf0, 0xd8, 0xd6, 0xc5, 0x11, 0xb1,
	0x2d, 0x8d, 0x24, 0x03, 0xe6, 0x2b, 0xf8, 0x18, 0x3e, 0x82, 0x32, 0xb3, 0xd5, 0x96, 0x3b, 0xc9,
	0x27, 0xec, 0x0f, 0xec, 0x58, 0xb2, 0x77, 0xdd, 0xe9, 0x1e, 0x9d, 0x7b, 0xce, 0xbd, 0x3a, 0x42,
	0xaf, 0xc4, 0x91, 0x05, 0x91, 0x10, 0x92, 0xff, 0x04, 0x1a, 0x26, 0x20, 0x35, 0xfb, 0xce, 0x92,
	0x48, 0x83, 0xf2, 0x85, 0xe4, 0x9a, 0x63, 0xff, 0x0f, 0x4b, 0x63, 0x80, 0x28, 0xcb, 0x58, 0x54,
	0x24, 0xe0, 0x53, 0xa6, 0xb4, 0x64, 0x71, 0xa9, 0x81, 0x26, 0x3c, 0x17, 0x16, 0xcd, 0x80, 0xa6,
	0x20, 0x7d, 0x71, 0x64, 0x2f, 0x97, 0x09, 0x57, 0x39, 0x57, 0xa1, 0xe9, 0x0e, 0x6c, 0x61, 0xa5,
	0xde, 0xdc, 0xf6, 0xd1, 0x62, 0xd3, 0x58, 0x7d, 0xe8, 0x38, 0x61, 0x82, 0x46, 0xaa, 0x8c, 0x7f,
	0x40, 0xa2, 0x89, 0xb3, 0x72, 0xd6, 0x93, 0x5d, 0x5b, 0xe2, 0x77, 0x68, 0xd6, 0x1c, 0xc3, 0x23,
	0x54, 0x21, 0xa3, 0xa4, 0x6f, 0x08, 0xd3, 0x06, 0xfd, 0x0c, 0xd5, 0x27, 0x8a, 0x97, 0x68, 0x2c,
	0x20, 0x37, 0xd3, 0x93, 0x47, 0x56, 0x40, 0x40, 0x5e, 0x5b, 0xe0, 0xb7, 0xe8, 0xa9, 0x02, 0xc9,
	0xa2, 0x2c, 0x2c, 0xca, 0x3c, 0x06, 0x49, 0x1e, 0x37, 0xfd, 0x06, 0xfc, 0x62, 0x30, 0xfc, 0x1c,
	0x0d, 0x99, 0x52, 0x25, 0x48, 0x32, 0x30, 0xb7, 0x4d, 0x85, 0xd7, 0x68, 0x1e, 0x95, 0xfa, 0xc0,
	0x25, 0xd3, 0x55, 0xeb, 0x3f, 0x34, 0x8c, 0xd9, 0x3d, 0x6e, 0x27, 0x78, 0x8d, 0xa6, 0x92, 0x73,
	0x1d, 0xb6, 0x6b, 0x8c, 0x0c, 0xeb, 0x49, 0x8d, 0xed, 0x9b, 0x55, 0x3c, 0xf4, 0xac, 0x4b, 0x69,
	0xf5, 0xc6, 0x86, 0x39, 0xef, 0x30, 0xad, 0xe2, 0x0b, 0x34, 0x62, 0x2a, 0xac, 0x61, 0x32, 0x59,
	0x39, 0xeb, 0x71, 0x3d, 0xd4, 0x8e, 0x73, 0x8d, 0x7d, 0x34, 0xe0, 0xbf, 0x0a, 0x90, 0x04, 0xd5,
	0x9d, 0x5b, 0x72, 0xf5, 0xcf, 0x5b, 0x34, 0xcf, 0xbc, 0xa1, 0x54, 0x82, 0x52, 0x7b, 0x2d, 0x59,
	0x91, 0xee, 0x2c, 0x6d, 0xfb, 0xed, 0xff, 0xd9, 0x75, 0x4e, 0x67, 0xd7, 0xb9, 0x39, 0xbb, 0xce,
	0xdf, 0x8b, 0xdb, 0x3b, 0x5d, 0xdc, 0xde, 0xf5, 0xc5, 0xed, 0x7d, 0xfd, 0x98, 0x32, 0x7d, 0x28,
	0x63, 0x3f, 0xe1, 0x79, 0x60, 0x53, 0xf6, 0xda, 0x98, 0x83, 0x4e, 0xcc, 0xde, 0x43, 0xce, 0x9e,
	0x0d, 0x3a, 0xf8, 0x1d, 0xd4, 0xdf, 0x46, 0x57, 0x02, 0x54, 0x3c, 0x34, 0xe1, 0xbe, 0xbf, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x26, 0x49, 0xd3, 0x91, 0x4a, 0x02, 0x00, 0x00,
}

func (m *ApprovedCertificates) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApprovedCertificates) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApprovedCertificates) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x52
	}
	if m.IsRoot {
		i--
		if m.IsRoot {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.RootSubjectKeyId) > 0 {
		i -= len(m.RootSubjectKeyId)
		copy(dAtA[i:], m.RootSubjectKeyId)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.RootSubjectKeyId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.RootSubject) > 0 {
		i -= len(m.RootSubject)
		copy(dAtA[i:], m.RootSubject)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.RootSubject)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.AuthorityKeyId) > 0 {
		i -= len(m.AuthorityKeyId)
		copy(dAtA[i:], m.AuthorityKeyId)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.AuthorityKeyId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SerialNumber) > 0 {
		i -= len(m.SerialNumber)
		copy(dAtA[i:], m.SerialNumber)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.SerialNumber)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PemCert) > 0 {
		i -= len(m.PemCert)
		copy(dAtA[i:], m.PemCert)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.PemCert)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SubjectKeyId) > 0 {
		i -= len(m.SubjectKeyId)
		copy(dAtA[i:], m.SubjectKeyId)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.SubjectKeyId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintApprovedCertificates(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintApprovedCertificates(dAtA []byte, offset int, v uint64) int {
	offset -= sovApprovedCertificates(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ApprovedCertificates) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	l = len(m.SubjectKeyId)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	l = len(m.PemCert)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	l = len(m.SerialNumber)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	l = len(m.AuthorityKeyId)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	l = len(m.RootSubject)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	l = len(m.RootSubjectKeyId)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	if m.IsRoot {
		n += 2
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovApprovedCertificates(uint64(l))
	}
	return n
}

func sovApprovedCertificates(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApprovedCertificates(x uint64) (n int) {
	return sovApprovedCertificates(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ApprovedCertificates) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovedCertificates
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApprovedCertificates: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApprovedCertificates: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubjectKeyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubjectKeyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PemCert", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PemCert = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SerialNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SerialNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityKeyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorityKeyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootSubject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootSubject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootSubjectKeyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootSubjectKeyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRoot", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsRoot = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApprovedCertificates(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovedCertificates
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApprovedCertificates(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApprovedCertificates
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApprovedCertificates
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApprovedCertificates
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApprovedCertificates
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApprovedCertificates
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApprovedCertificates        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApprovedCertificates          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApprovedCertificates = fmt.Errorf("proto: unexpected end of group")
)
